### ISSUE TITLE
Create or Update API with 0 Retries

### ISSUE THREAD

**Issue by mfamador** [kevholditch/gokong#7] opened 2018-03-17 09:48 UTC
Hi!
I am using the terraform-provider-kong (thank you so much for it, btw!) and I'm having an issue that I was wondering if you could give me some pointers on how to proceed.

I need to set Retries to 0 when creating or updating an API, but the field "retries" disappears in the JSON Marshalling process, basically because retries=0 will be considered empty, not being then passed in the payload to Kong and falling back to the Retries default value (5) of the Kong itself.

To better explain what I mean I've added the following tests to api_tests.go that in my opinion they should pass both. 
The first one is failing due to what I've said before and the second is passing and I think it is the correct behavior - when omitted it gets the kong defaults.

```
func Test_ApisCreateZeroRetries(t *testing.T) {
	apiRequest := &ApiRequest{
		Name:                   "zero-retries-test-" + uuid.NewV4().String(),
		Hosts:                  []string{"example.com"},
		Uris:                   []string{"/example"},
		Methods:                []string{"GET", "POST"},
		UpstreamUrl:            "http://localhost:4140/testservice",
		Retries:                0,
	}
	result, err := NewClient(NewDefaultConfig()).Apis().Create(apiRequest)
	assert.Nil(t, err)
	assert.NotNil(t, result)

	assert.Equal(t, apiRequest.Retries, result.Retries)
}

func Test_ApisCreateDefaultRetries(t *testing.T) {
	apiRequest := &ApiRequest{
		Name:                   "no-retries-test-" + uuid.NewV4().String(),
		Hosts:                  []string{"example.com"},
		Uris:                   []string{"/example"},
		UpstreamUrl:            "http://localhost:4140/testservice",
		Methods:                []string{"GET", "POST"},
	}
	result, err := NewClient(NewDefaultConfig()).Apis().Create(apiRequest)
	assert.Nil(t, err)
	assert.NotNil(t, result)

	assert.Equal(t, 5, result.Retries)
}
```
If we remove the "omitempty" in ApiRequest struct then the first test passes but the second one fails now because it will add "retries":0" to the payload.
```
type ApiRequest struct {
	Name                   string   `json:"name"`
	Hosts                  []string `json:"hosts,omitempty"`
	Uris                   []string `json:"uris,omitempty"`
	Methods                []string `json:"methods,omitempty"`
	UpstreamUrl            string   `json:"upstream_url"`
	StripUri               bool     `json:"strip_uri"`
	PreserveHost           bool     `json:"preserve_host"`
	Retries                int      `json:"retries"`
	UpstreamConnectTimeout int      `json:"upstream_connect_timeout,omitempty"`
	UpstreamSendTimeout    int      `json:"upstream_send_timeout,omitempty"`
	UpstreamReadTimeout    int      `json:"upstream_read_timeout,omitempty"`
	HttpsOnly              bool     `json:"https_only"`
	HttpIfTerminated       bool     `json:"http_if_terminated"`
}
```
```
{
    "created_at":1521279579200,
    "strip_uri":false,
    "id":"e0507fa4-14d3-435e-bdba-9d7dbbc6d190",
    "hosts":["example.com"],
    "name":"no-retries-test-31ffbdb2-dba9-4360-9947-aa127d6a643c",
    "methods":["GET","POST"],
    "http_if_terminated":false,
    "preserve_host":false,
    "upstream_url":"http:\/\/localhost:4140\/testservice",
    "uris":["\/example"],
    "upstream_send_timeout":60000,
    "upstream_connect_timeout":60000,
    "upstream_read_timeout":60000,
    "retries":0,
    "https_only":false'
}
```

Thank you so much!

**Comment by kevholditch** [comment] 2018-03-19 08:37
Hey @mfamador, no worries glad you are getting use out of the provider!

I see exactly what you mean with regards to the issue.  As you say this is due to the way that default values work in go.  We will have to think about how we can change `gokong` so that it supports passing in `0` retries.

**Comment by kevholditch** [comment] 2018-03-19 13:44
Just been thinking about this some more and its quite a conundrum we have.  The crux of the issue is that `gokong` has no way to tell the difference between the user not setting the value for retries and the user setting it to 0 (as your tests prove).

We need a way for you to signal that you actually omitting it and want the default behaviour (5 retries) vs you are explicitly setting it to `0`.  This problem also applies to every field on every request object where the `Kong` default differs from the `go` default for that type.

I'd like any solution to this to be generic and not just a workaround for just this field.  It would be good to fix this issue everywhere. 

Any suggestions welcome

**Comment by mfamador** [comment] 2018-03-20 07:50
Hi @kevholditch!
Yes, we think that we have the same problem in other fields, (like when trying to remove an anonymous user from basic auth plugin config, the plugin does not actually remove it from kong configuration) we should get a generic solution, I agree.
I'm not that proficient in `go`, but one solution perhaps could be using pointers, I'm not sure if it's feasible.
Thank you for your help!

**Comment by kevholditch** [comment] 2018-03-23 16:15
@mfamador I have fixed this by changing the `ApiRequest` struct to take `retries` as a string.  This is automatically handled by kong.  This allows me to tell if you set it to 0 or do not set it as I will get the string "0" or "".

With this in place there wasn't much to change in the terraform-kong provider.  It still takes retries as an int but I have set the default value to 5.  Meaning if you dont set it I will receive 5.  So in affect when you are using the terraform provider you will always set a value for retries but it should now work.

I am closing this issue, if you could try out the new build of the [terraform kong provider](https://github.com/kevholditch/terraform-provider-kong/releases/tag/v0.14.0) as I believe it is fixed.  I have updated the api test to create an api with the default retry count (not specify it) and then update it to 0 and it works fine.

**Closed by kevholditch** 2018-03-23 16:15 UTC

**Comment by volodymyrpavlenko** [comment] 2018-03-26 14:15
Hi @kevholditch, this unfortunately does not cover another issue with empty values, when we need to change string value to empty, for example, when disallowing the anonymous consumer for an auth plugin. 

For example, we first setup anonymous consumer like this:
`resource "kong_plugin" "basic_auth" {
  api_id = "${kong_api.api.id}"
  name = "basic-auth"

  config = {
    anonymous = "${kong_consumer.api_anonymous.id}"
    hide_credentials = "true"
  }
}`

This works without issues, but when we try to remove anonymous user by applying this config:
`resource "kong_plugin" "basic_auth" {
  api_id = "${kong_api.api.id}"
  name = "basic-auth"

  config = {
    hide_credentials = "true"
  }
}`

It simply does not get removed, though terraform detects the change.
A workaround would be to delete the whole plugin config and then re-apply without anonymous user.

It seems that using pointers and introducing null value as an indication of empty field would be a solution, but I am far from being good in go.

Do you have any other solutions?

**Comment by kevholditch** [comment] 2018-03-26 14:21
@volodymyrpavlenko yep all we need to do is set `force-recreate` to true for the `config` parameter on the `kong_plugin` resource.  That should fix it.  If you create a test to reproduce this issue then you can confirm that setting force recreate to `true` fixes it.

Basically what force recreate does it forces kong to delete and then create the resource rather than updating it in place.

**Comment by volodymyrpavlenko** [comment] 2018-03-26 14:24
Does it mean that for a very short period of time the resource would be unavailable? 

We have quite high load on our services, ~600 req/s. Even 1 second downtime would fail this many requests.

**Comment by kevholditch** [comment] 2018-03-26 15:13
yes it would mean a short period where the resource would not be available.

This case is a bit tricky as you are effectively removing the config property but what's happening is that because terraform is passing the provider the map without the old value in when we build the `PATCH` call we do not have the `anonymous` field therefore the patch will not remove it.

Maybe we need to be a bit more clever and when doing an update we call over to `kong` to get the current config then we could include empty fields in the `PATCH` requests.  We would need to build tests around this as there may be some reasons this wouldnt work
